export const AllshoeData =[
    {   
        "category":"men",
        "id":1,
        "name":"Men’s Black Running",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-005.jpg",
        "price":209.56,
    },
    {
        "category":"men",
        "id":2,
        "name":"Men’s Classic Blue",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-019.jpg",
        "price":  347.89,
    },
    {        "category":"men",

        "id":3,
        "name":"Men’s Classic Mint",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-020.jpg",
        "price": 287.89 ,
    },
    {        "category":"men",

        "id":4,
        "name":"Men’s Earth-Tone Sneaker",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-017.jpg",
        "price":   329.99,
    },
    {        "category":"men",

        "id":5,
        "name":"Men’s Green Running",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-007.jpg",
        "price": 239.99,
    },
    {        "category":"men",

        "id":6,
        "name":"Men’s Moonstone Sneaker",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-018.jpg",
        "price":   329.99,
    },
    {        "category":"women",

        "id":7,
        "name":"Women’s Blue Training",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-003.jpg",
        "price":    249.99,
    },
    { "category":"women",
        "id":8,
        "name":"Women’s Candy City Run",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-014.jpg",
        "price":     249.99,
    },
    { "category":"women",
        "id":9,
        "name":"Women’s Cream Suede",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-015.jpg",
        "price":  199.99    ,
    },
    { "category":"women",
        "id":10,
        "name":"Women’s Green Training",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-001.jpg",
        "price":       199.99,
    },
    { "category":"women",
        "id":11,
        "name":"Women’s Tosca City Run",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-012.jpg",
        "price": 249.99,
    },
    { "category":"women",
        "id":12,
        "name":"Women’s Mint Sneaker",
        "imgpath":"https://websitedemos.net/recycled-shoe-store-04/wp-content/uploads/sites/983/2021/11/recycled-shoe-product-image-010.jpg",
        "price":  249.99     ,
    },

    
    ]